# Generated by Django 3.0.8 on 2021-07-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': (('can_create_menu', 'Can create menu'), ('can_edit_menu', 'Can edit menu'))},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('can_see_orders', 'Can see orders'),)},
        ),
        migrations.AlterField(
            model_name='menuoptions',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_option', to='lunch.Menu'),
        ),
    ]
