# Generated by Django 3.0.8 on 2021-07-03 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20210702_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
